version: '3.1'

services:

  postgresdb:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgresdb
    ports:
      - 8070:8080
